# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_state.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10game_state.proto\x12\x0c\x43ore.Network\"-\n\nVector3Msg\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\x9d\x01\n\x0cTransformMsg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x08position\x18\x02 \x01(\x0b\x32\x18.Core.Network.Vector3Msg\x12*\n\x08rotation\x18\x03 \x01(\x0b\x32\x18.Core.Network.Vector3Msg\x12\'\n\x05scale\x18\x04 \x01(\x0b\x32\x18.Core.Network.Vector3Msg\"t\n\nCommandMsg\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\x12\x30\n\x0evector_payload\x18\x04 \x01(\x0b\x32\x18.Core.Network.Vector3Msg\"_\n\x0cGameStateMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12,\n\x08\x65ntities\x18\x02 \x03(\x0b\x32\x1a.Core.Network.TransformMsg\x12\x0e\n\x06status\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTOR3MSG']._serialized_start=34
  _globals['_VECTOR3MSG']._serialized_end=79
  _globals['_TRANSFORMMSG']._serialized_start=82
  _globals['_TRANSFORMMSG']._serialized_end=239
  _globals['_COMMANDMSG']._serialized_start=241
  _globals['_COMMANDMSG']._serialized_end=357
  _globals['_GAMESTATEMSG']._serialized_start=359
  _globals['_GAMESTATEMSG']._serialized_end=454
# @@protoc_insertion_point(module_scope)
